mongodata:
  image: mongo:3.4
  volumes:
    - ./data:/data/db
mongo:
  image: mongo:3.4
  ports:
    - "27017:27017"
  command: --port=27017
mongo-seed:
  image: mongo:3.4
  volumes_from:
    - mongodata
  links:
    - mongo
  command: >
    mongoimport -d moto -c helmet 
    --drop --host=0.0.0.0:27017
    --jsonArray /data/db/lids.json 